var Bank = require("./routers/Bank.js");
app.use("/Bank", Bank);
var BankAccount = require("./routers/BankAccount.js");
app.use("/BankAccount", BankAccount);
var EletricityConnection = require("./routers/EletricityConnection.js");
app.use("/EletricityConnection", EletricityConnection);
var EletricityBill = require("./routers/EletricityBill.js");
app.use("/EletricityBill", EletricityBill);
var EletricityBillPayment = require("./routers/EletricityBillPayment.js");
app.use("/EletricityBillPayment", EletricityBillPayment);
var RentedProperty = require("./routers/RentedProperty.js");
app.use("/RentedProperty", RentedProperty);
var Rent = require("./routers/Rent.js");
app.use("/Rent", Rent);
var Voucher = require("./routers/Voucher.js");
app.use("/Voucher", Voucher);
var CashVoucher = require("./routers/CashVoucher.js");
app.use("/CashVoucher", CashVoucher);
var Note = require("./routers/Note.js");
app.use("/Note", Note);
var VendorNotes = require("./routers/VendorNotes.js");
app.use("/VendorNotes", VendorNotes);
var Invoice = require("./routers/Invoice.js");
app.use("/Invoice", Invoice);
var InvoiceItem = require("./routers/InvoiceItem.js");
app.use("/InvoiceItem", InvoiceItem);
var InvoicePayment = require("./routers/InvoicePayment.js");
app.use("/InvoicePayment", InvoicePayment);
var InvoicePrint = require("./routers/InvoicePrint.js");
app.use("/InvoicePrint", InvoicePrint);
var ProductStock = require("./routers/ProductStock.js");
app.use("/ProductStock", ProductStock);
var Stock = require("./routers/Stock.js");
app.use("/Stock", Stock);
var Employee = require("./routers/Employee.js");
app.use("/Employee", Employee);
var Attendance = require("./routers/Attendance.js");
app.use("/Attendance", Attendance);
var SalaryPayment = require("./routers/SalaryPayment.js");
app.use("/SalaryPayment", SalaryPayment);
var DailySale = require("./routers/DailySale.js");
app.use("/DailySale", DailySale);
var DueBill = require("./routers/DueBill.js");
app.use("/DueBill", DueBill);
var DueBillRecovered = require("./routers/DueBillRecovered.js");
app.use("/DueBillRecovered", DueBillRecovered);
var Store = require("./routers/Store.js");
app.use("/Store", Store);
var Company = require("./routers/Company.js");
app.use("/Company", Company);
var Salesman = require("./routers/Salesman.js");
app.use("/Salesman", Salesman);
var User = require("./routers/User.js");
app.use("/User", User);
var Bank = require("./routers/Bank.js");
app.use("/Bank", Bank);
var BankAccount = require("./routers/BankAccount.js");
app.use("/BankAccount", BankAccount);
var EletricityConnection = require("./routers/EletricityConnection.js");
app.use("/EletricityConnection", EletricityConnection);
var EletricityBill = require("./routers/EletricityBill.js");
app.use("/EletricityBill", EletricityBill);
var EletricityBillPayment = require("./routers/EletricityBillPayment.js");
app.use("/EletricityBillPayment", EletricityBillPayment);
var RentedProperty = require("./routers/RentedProperty.js");
app.use("/RentedProperty", RentedProperty);
var Rent = require("./routers/Rent.js");
app.use("/Rent", Rent);
var Voucher = require("./routers/Voucher.js");
app.use("/Voucher", Voucher);
var CashVoucher = require("./routers/CashVoucher.js");
app.use("/CashVoucher", CashVoucher);
var Note = require("./routers/Note.js");
app.use("/Note", Note);
var VendorNote = require("./routers/VendorNote.js");
app.use("/VendorNote", VendorNote);
var Invoice = require("./routers/Invoice.js");
app.use("/Invoice", Invoice);
var InvoiceItem = require("./routers/InvoiceItem.js");
app.use("/InvoiceItem", InvoiceItem);
var InvoicePayment = require("./routers/InvoicePayment.js");
app.use("/InvoicePayment", InvoicePayment);
var InvoicePrint = require("./routers/InvoicePrint.js");
app.use("/InvoicePrint", InvoicePrint);
var Employee = require("./routers/Employee.js");
app.use("/Employee", Employee);
var Attendance = require("./routers/Attendance.js");
app.use("/Attendance", Attendance);
var SalaryPayment = require("./routers/SalaryPayment.js");
app.use("/SalaryPayment", SalaryPayment);
var Store = require("./routers/Store.js");
app.use("/Store", Store);
var Company = require("./routers/Company.js");
app.use("/Company", Company);
var Salesman = require("./routers/Salesman.js");
app.use("/Salesman", Salesman);
var User = require("./routers/User.js");
app.use("/User", User);
